trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '**/BolRetailerAPI.csproj'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration release'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    projects: '**/BolRetailerAPI.csproj'

- task: NuGetCommand@2
  inputs:
    command: Push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet'
    packagesToPack: '**/BolRetailerAPI.csproj'
    versioningScheme: 'off'

